pipeline {
    agent any

    tools {
        maven 'Maven 3.6.3' // Nombre de la instalación de Maven configurada en Jenkins
        jdk 'JDK 11'        // Nombre de la instalación de JDK configurada en Jenkins
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/tu-usuario/tu-repositorio.git'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn clean install'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit '**/target/surefire-reports/*.xml' // Publicar resultados de pruebas
                }
            }
        }
        stage('Package') {
            steps {
                sh 'mvn package'
            }
        }
        stage('Deploy') {
            steps {
                // Agrega tus pasos de despliegue aquí
                echo 'Despliegue realizado'
            }
        }
    }

    post {
        success {
            echo 'Build completado exitosamente'
        }
        failure {
            echo 'Build fallido'
        }
        always {
            cleanWs() // Limpiar el workspace después de cada build
        }
    }
}
